- id: wazo-copyright-check
  name: check copyright notices
  description: check wazo copyright notices in source file headers of updated file
  language: script
  entry: git-hooks/copyright-check
  stages: [commit, push, manual]
- id: wazo-changelog-check
  name: update debian changelog
  description: check that debian/changelog file has been updated along with commit
  language: script
  entry: git-hooks/changelog-check
  stages: [commit, push, manual]
- id: wazo-local-docker-volume-check
  name: check local docker volume
  description: check usage of LOCAL_GIT_REPOS in files to commit
  language: script
  entry: git-hooks/local-docker-volume-check
  stages: [commit, push, manual]
