- hosts: jenkinses
  remote_user: root
  tasks:
    - name: Install Jenkins
      apt:
        name: jenkins
    - name: Install openjdk-8-jre for display warnings-plugin graphs
      apt:
        name: openjdk-8-jre
